ResidenciaTICBrisa/T2G1-IA-Gloria

- backend/prisma/schema.prisma
- backend/src/app.ts
- backend/src/controllers/authorization-controller.ts
- backend/src/repositories/authorization-repository.ts
- backend/src/routers/authorization-routers.ts
- backend/src/services/authorization-services.ts
Co-authored-by: Ana Júlia <anaju.batsouza@gmail.com>
Co-authored-by: Kece Line <keceline74@gmail.com>
> feat: capturing user ip

- backend/prisma/migrations/20240514164820_add_user_ip/migration.sql
- backend/prisma/migrations/20240514170257_fix_type_id_user/migration.sql
- backend/prisma/migrations/20240514173538_fix/migration.sql
- backend/prisma/migrations/20240514174510_fix/migration.sql
- backend/prisma/migrations/20240514183322_add_unique_userid/migration.sql
- backend/prisma/schema.prisma
- backend/src/controllers/authorization-controller.ts
- backend/src/protocols.ts
- backend/src/repositories/authorization-repository.ts
- backend/src/repositories/formAboutViolencePage-repository.ts
- backend/src/repositories/formClassifyViolencePage-repository.ts
- backend/src/repositories/formStatePage-repository.ts
- backend/src/services/authorization-services.ts
- backend/src/services/formAboutViolencePage-service.ts
- backend/src/services/formStatePage-service.ts
- backend/src/sql files/database_structure_v3.txt
- ajustes nos tipos das colunas (id do usuário deve ser bigint), 
- as funções do repositório agora são de update 
- todos os métodos post recebem o id_user
- adiciona função no authorization-repository para criar linha na tabela de ocorrência
> Correcoes backend

- frontend/src/pages/FormStatePage.tsx
- frontend/src/pages/MapFilterPage.tsx
- frontend/src/styles/Footer.css
- frontend/src/styles/MapPage.css
Adição do filtro da página map-filter, sendo necessárias correções de style 
Adição do input de estado na página Form-state-page, faltando mostrar apenas as cidades pertencentes ao estado selecionado
> Mapa com filtro 

- backend/prisma/migrations/20240528195030_add_city/migration.sql
- backend/prisma/schema.prisma
- backend/src/protocols.ts
- backend/src/repositories/formStatePage-repository.ts
- backend/src/services/formStatePage-service.ts
Realizei as mudanças para o envio e armazenamento do banco do campo "cidade" do formulário. É armazenada em uma coluna da `Occurrence` do tipo string.
> Adiciona campo cidade

- frontend/src/App.css
- frontend/src/components/HeaderMap.tsx
- frontend/src/pages/MapAddress.tsx
- frontend/src/pages/MapFilterPage.tsx
- frontend/src/pages/MapPage.tsx
- frontend/src/styles/HomePage.css
Alinhamento do botão de voltar com a logo do glória de forma horizontal 
Criação do componente HeaderMap e substituição do código nas páginas do mapa
Ainda falta: alinhar a logo no centro nas três páginas de mapa
> Alinhamento horizontal dos itens do header 

- backend/prisma/migrations/20240604191835_upd_structure_v5/migration.sql
- backend/prisma/schema.prisma
- backend/src/repositories/authorization-repository.ts
- backend/src/repositories/formAboutViolencePage-repository.ts
- backend/src/repositories/formClassifyViolencePage-repository.ts
- backend/src/repositories/formStatePage-repository.ts
- backend/src/repositories/mapFilterPage-repository.ts
- backend/src/repositories/mapPage-repository.ts
- backend/src/routers/authorization-router.ts
- backend/src/services/formStatePage-service.ts
- backend/src/sql files/database_structure_v5_04-06.txt
- backend/src/sql files/preenchimento das tabelas
- Atualização dos nomes da tabelas, colunas e chaves estrangeiras do banco de dados para padronizar.
- Deleta a tabel `access`, que não é mais necessária. 
- Cria a migração.
- Atualização das funções de repositório correspondetes
- Rota `unauthorize-location` foi comentada até futuras atualizações.
> Atualização da Estrutura do Banco de Dados.

- frontend/package-lock.json
- frontend/package.json
- frontend/src/main.tsx
- frontend/src/pages/FormAboutViolencePage.tsx
Fizemos o ajuste de que, quando a ocorrência é preenchida, os dados não são enviados diretamente para o BD.
> Conecta back front

- backend/src/protocols.ts
- backend/src/repositories/formStatePage-repository.ts
- backend/src/services/formStatePage-service.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/FormStatePage.tsx
correções no backend e integração com o front. Adicionamos uma flag no front indicando se os dados estão adequados para o back ou não.
> Form state back

- frontend/src/pages/AuthorizeLocalizationPage.tsx
Co-authored-by: Kece <keceline74@gmail.com>
Co-authored-by: Ana Júlia <anaju.batsouza@gmail.com>
> fix: authorization router excluded

- backend/src/controllers/formAboutViolencePage-controller.ts
- backend/src/controllers/formClassifyViolencePage-controller.ts
- backend/src/controllers/formStatePage-controller.ts
- backend/src/controllers/mapPage-controller.ts
- backend/src/protocols.ts
- backend/src/repositories/mapPage-repository.ts
- backend/src/routers/mapPage-router.ts
- backend/src/services/formAboutViolencePage-service.ts
- backend/src/services/formClassifyViolencePage-service.ts
- backend/src/services/formStatePage-service.ts
- backend/src/services/mapPage-services.ts
- backend/tsconfig.json
Ajustes no backend da página mapPage, onde é realizada a submissão da ocorrência no banco de dados. Gera o id_user para o fingerprint (evitando duplicatas), valida novamente os dados (por uma questão de segurança), adiciona os dados na tabela de ocorrência e incrementa o contador de ocorrência por estado. Também alterei os nomes das funções de serviço
> Back map page

- frontend/src/pages/AuthorizeLocalizationPage.tsx
- frontend/src/pages/FormStatePage.tsx
Foi corrigida a **navegação para que a página de autorizar localização direcione ao valor do componente correspondente**, de acordo com a página anterior.
Na página AuthorizeLocalization, foi criada uma variável na constante handleNotAuthorize para armazenar o valor de FormStateValue.
Na página FormStatePage, foi implementado um useEffect para capturar e utilizar o valor atribuído a essa variável.
> fix: fixing component navigation FormStateOptions

- backend/src/services/formClassifyViolencePage-service.ts
- frontend/src/pages/FormClassifyViolencePage.tsx
Foram incrementadas as opções de violência moral no frontend e corrigida a função no backend que classifica essas opções de acordo com o tipo de violência sofrida.
> Classify violence correcao

- frontend/.env
- frontend/.env.example
- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/AuthorizeLocalizationPage.tsx
- frontend/src/pages/FormAboutViolencePage.tsx
- frontend/src/pages/FormClassifyViolencePage.tsx
- frontend/src/pages/FormStatePage.tsx
Co-authored-by: Kece <keceline74@gmail.com>
Co-authored-by: Ana Júlia <anaju.batsouza@gmail.com>
> feat: add .env file to frontend

- backend/src/controllers/authorization-controller.ts
- backend/src/routers/authorization-router.ts
- backend/src/services/authorization-services.ts
- frontend/src/pages/MapPage.tsx
- frontend/src/styles/MapPage.css
Adiciona as informações da violência na tela de resumo
> feat: info violence in MapPage

- frontend/src/App.css
- frontend/src/pages/FormAboutViolencePage.tsx
- frontend/src/pages/MapAddress.tsx
Mudanças realizadas no commit:
- O botão que direciona para a próxima página no mapa teve seu texto alterado de "Próximo" para "Confirmo este local".
- As mensagens de alerta agora estão posicionadas abaixo de cada caixa de seleção, em vez de no final da página.
- O zoom do mapa, ao abrir a página MapAddress, foi ajustado para exibir as quadras de forma mais detalhada.
**Observação:** todas as mudanças deste commit foram solicitadas pelo stakeholder na reunião realizada em 4 de julho de 2024.
> fixing button, map zoom and error message

- backend/src/repositories/mapFilterPage-repository.ts
- frontend/src/pages/AuthorizeLocalizationPage.tsx
- frontend/src/pages/FormStatePage.tsx
- frontend/src/pages/MapFilterPage.tsx
Na tela `map-filter`, agora são mostrados os pins nas coordenadas já registradas na tabela de ocorrências. Além disso, só são mostrados as ocorrências dos últimos 5 anos, conforme solicitado pelo cliente. Ainda não há diferença entre os pins de cada tipo de violência e o filtro não foi implementado.
> Visualização dos Pins na tela map-filter

- frontend/src/components/Pin.tsx
- frontend/src/pages/MapFilterPage.tsx
Foi feito com que a visualização dos pins no mapa seja feita de acordo com a seleção dos tipos de violência que o usuário fez.
E foi colocado pop-up em cada pin com a descrição do tipo de violência.
> Filtro map filter

- frontend/src/components/LegendMapFilter.tsx
- frontend/src/pages/MapFilterPage.tsx
- frontend/src/styles/LegendMapFilter.css
Adicionamos a legenda das cores dos pins. Faltou serem correspondentes as cores dos pins, contudo ainda haverá revisão das cores dos pins.
> Legenda na tela map-filter

- frontend/src/components/LegendMapFilter.tsx
- frontend/src/pages/MapFilterPage.tsx
- frontend/src/styles/LegendMapFilter.css
Adicionei a opção de abrir e fechar a legenda no componente LegendMapFilter
> adding subtitle open and close

- backend/prisma/migrations/20240717192206_merge_date_time_columns/migration.sql
- backend/prisma/schema.prisma
- backend/src/protocols.ts
- backend/src/repositories/mapFilterPage-repository.ts
- backend/src/repositories/mapPage-repository.ts
- backend/src/services/formAboutViolencePage-service.ts
- backend/src/services/mapPage-services.ts
- frontend/src/pages/FormAboutViolencePage.tsx
- frontend/src/pages/MapPage.tsx
- Captura do fuso horário do usuário;
- Junção da coluna date_violence com a coluna time_violence para a coluna datetime_violence com fuso horário. 
- Alteração das mensagens de erro para horas futuras (adição ao final da tela uma mensagem específica);
- Adequações nas funções de serviço e repositório.
> Pega fuso horário do usuário 

- frontend/src/components/FormIndex.tsx
- frontend/src/pages/AuthorizeLocalizationPage.tsx
- frontend/src/pages/FormStatePage.tsx
- remoção do index das telas de autorização e de estado;
- Mudança para apenas 2 index na tela de formulário.
> feat: index

- frontend/src/App.tsx
- frontend/src/components/Header.tsx
- frontend/src/components/HeaderMap.tsx
- frontend/src/components/HeaderThankyou.tsx
- frontend/src/pages/WhatToDoPage.tsx
- frontend/src/styles/HomePage.css
A página inicial identificada como "Home Page", foi analisada e considerada desnecessária para o fluxo de navegação do site. Portanto, foi removida do sistema para simplificar a experiência do usuário e melhorar a eficiência do site.
> Remover home page

- frontend/src/pages/MapAddress.tsx
- frontend/src/pages/MapFilterPage.tsx
- frontend/src/pages/MapPage.tsx
- frontend/src/styles/MapFilter.css
- frontend/src/styles/MapPage.css
- frontend/src/styles/MapPageAddress.css
Adicionamos botão de voltar nas telas`map-address`, na `map-page` e na `map-filter`
> feat: back button on screens with map

- frontend/src/App.tsx
- frontend/src/components/Header.tsx
- frontend/src/main.tsx
- frontend/src/pages/EmergencyPage.tsx
Correção pop-up tela de emergência.
> fix: popup emergency page

- frontend/src/pages/EmergencyPage.tsx
Correção tela emergency page, ao clicar para ligar e estiver em um desktop o pop-up reaparece.
> fix: emergency page
